### ISSUE TITLE
---

### ISSUE THREAD

**Issue by QYG2297248353** [guqing/halo-plugin-colorless#5]
---

**Comment by QYG2297248353** [comment]
@guqing 是不是Bug呢

**Comment by guqing** [comment]
这与本插件无关吧，缓存插件影响的东西就多了，发布了文章或者瞬间等操作都是不会自动更新页面的需要手动刷新缓存

**Comment by QYG2297248353** [comment]
> 这与本插件无关吧，缓存插件影响的东西就多了，发布了文章或者瞬间等操作都是不会自动更新页面的需要手动刷新缓存

那好吧，只能手动操作了
